version: "3.9"

services:
  backend:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000" # localhost:8000 -> contenedor:8000
    volumes:
      - .:/app  # para desarrollo: refleja cambios locales en el contenedor
    depends_on:
      - db
 

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    ports:
      - "3307:3306" # expone en 3307 para no chocar con MySQL local
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
